# Generated by Django 5.2.4 on 2025-07-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(default='avatares/default.png', upload_to='avatares/'),
        ),
    ]
