# Generated by Django 5.2.4 on 2025-07-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_noticia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
