# Generated by Django 5.2.4 on 2025-07-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='pages/')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
